### ISSUE TITLE
Add Year Date to the article if possible?

### ISSUE THREAD

**Issue by tim-yao** [abhivaikar/howtheytest#114]
Thanks for this awesome project first! It does help me a lot! However, there is a problem that annoys me when I use this project. Not sure if others have the same issue as me.

**My problem is that some of the links are old(outdated) content, but we have no way to know which year the content links to is. The only way is to click and find out the blog post date on the linked page.**

**Current**
![Screen Shot 2022-06-06 at 10 40 58 am](https://user-images.githubusercontent.com/31641325/172077451-ed33f199-75b0-4de6-a61d-def1619514a3.png)

**Proposal**
Add a date field for each link.
![Screen Shot 2022-06-06 at 10 46 48 am](https://user-images.githubusercontent.com/31641325/172077706-0985417c-1e2e-45ec-924b-a5d21a18a4da.png)

**Benefit**
With this change, users are able to see which content is new and which is old(probably outdated). I guess a lot of users may be misled if they are not aware of the date of the content. We are here for learn the trends and how others testing now, not past.

**Comment by abhivaikar** [comment]
That's a great suggestion. Will try and come up with the changes. Since the list is pretty huge now it will take some time for me to update it. I'll be happy if you can contribute as well 😃

**Comment by tim-yao** [comment]
@abhivaikar Happy to help. I will try this week! 👨‍💻 
I think you can add this to the code review for new contributions. So we at least get new content with a date. 😸
