### ISSUE TITLE
Spotify https://engineering.atspotify.com/* are not working

### ISSUE THREAD

**Issue by airtonGit** [abhivaikar/howtheytest#39]
Hi,

I have tried some Spotify links like 
* https://engineering.atspotify.com/2019/11/18/test-flakiness-methods-for-identifying-and-dealing-with-flaky-tests/
* https://engineering.atspotify.com/2018/01/11/testing-of-microservices/
* https://engineering.atspotify.com/2015/06/25/rapid-check/
* https://engineering.atspotify.com/2019/11/18/test-flakiness-methods-for-identifying-and-dealing-with-flaky-tests/

All of them not working right now.

Best,
Airton

**Comment by abhivaikar** [comment]
Fixed
