### ISSUE TITLE
links open in same tab

### ISSUE THREAD

**Issue by markgoho** [abhivaikar/howtheytest#44]
I was expecting all links to open in a new tab so that I wouldn't lose my place in the list of testing articles. Can we add `target="_blank"` to all links?

Markdown doesn't really support this natively, so links would need to be written as html. 

Maybe this is more trouble than it's worth 🤷🏼‍♂️

**Comment by dennissterzenbach** [comment]
If target="_blank" then it should also respect the data protection by including rel="noopener noreferrer" i think.

But anyway having to rewrite it all seems a bit ugly. And it even sounds a bit more like an issue the markdown rendering should serve rather than all that maintenance effort.

**Comment by abhivaikar** [comment]
Hi @markgoho, thanks for reporting this issue. Can you give an example of link that is not opening in a new tab? When I checked I could see the links of articles/videos in the company list opening in new tab. 

Is it the contributors link? Because that's the only one which opens in the same tab.

**Comment by abhivaikar** [comment]
Also, @markgoho were you trying to open the links from the github readme itself or the website created for this project?

In case if you are using only the readme, you can try using the corresponding github website created for it: https://abhivaikar.github.io/howtheytest/#/

**Comment by markgoho** [comment]
Thanks @abhivaikar I didn't realize there was a website version of this list. All of those links open in new tabs and the experience is exactly what I expected. Thanks again for maintaining a great project like this!
