### ISSUE TITLE
Software Testing Trends 2021 – What can we expect?

### ISSUE THREAD

**Issue by apurv25** [abhivaikar/howtheytest#86]
With the latest developments in IT sector services, the sector of QA testing has seen significant improvement and growth. The implementation of emerging technologies has helped improve the process of software development, testing, design and deployment. With all of these processes in place, cost optimization is also a high concern for organizations worldwide.

Many changes are rendered through automated testing. From AI to ML, the shifting technology world is constantly innovating and making significant progress. Are you aware that the scale of the app testing industry in 2019 was over USD$ 40 billion? And is projected to rise by more than 6 percent at CAGR(Compound Annual Growth Rate) between 2020 and 2026?

Learn more in this [blog](https://bit.ly/3bZUPLA).

**Comment by abhivaikar** [comment]
Hello @apurv25!

I noticed that this issue is not related to the howtheytest repository. Since it is not relevant, I will be closing it. Thanks.

**Comment by apurv25** [comment]
No prob, thanks!
